### ISSUE TITLE
Interferes with HashLink export

### ISSUE THREAD

**Issue by ninjamuffin99** [Geokureli/Newgrounds#47]
Gives "FATAL ERROR : Failed to load library ssl.hdll"
I'm preeeetty sure it's something to do with http or something like that, I don't know too many details, just heard that could be an issue

**Comment by Geokureli** [comment]
I'm super unfamiliar with hashlink but I can try to look into this when I have time. could you copy whatever correspondence you had about the http thing?

**Comment by ninjamuffin99** [comment]
It was somewhere deep in the Haxe discord
https://discord.com/channels/162395145352904705/165234904815239168/727379401615998986
should be about here, u might be able to open this if you're logged into discord on your browser. Gama11 gives some the details on that

**Comment by Cheemsandfriends** [comment]
> 
> 
> Gives "FATAL ERROR : Failed to load library ssl.hdll" I'm preeeetty sure it's something to do with http or something like that, I don't know too many details, just heard that could be an issue

It's the lime thing that they didn't add the automatic thing with HL,
I don't think it has to do something with the NG API tho

**Comment by Geokureli** [comment]
@ninjamuffin99 i heard you're using hashlink to debug now, did you figure this issue out or is it still goving you trouble?

**Comment by Cheemsandfriends** [comment]
@Geokureli I Guess he did but Idk How he do it, Either way We need lime to copy and load the ssl.hdll File without manually putting it there so You can just test it like HTML5, Windows, Mac, etc.

**Comment by ninjamuffin99** [comment]
> 
> 
> @ninjamuffin99 i heard you're using hashlink to debug now, did you figure this issue out or is it still giving you trouble?

I think the work that was done in FNF that allowed easier and nicer separation of the NG api stuff make it so that I can debug in HL and not have any of the NG api stuff enabled until I'd need it (for making new releases)

**Comment by Geokureli** [comment]
Right i forgot about that, im still not able to use hashlink myself so it may be a while before i can address this. But yeah usually its just a good idea to disable NGio on hashlink since its for debugging anyway

**Comment by Cheemsandfriends** [comment]
So maybe it should add an exception for like `#if !hl` or something?

**Comment by MSGhero** [comment]
I can try this out since I use HL quite a bit now with heaps. There's an ssl.hdll in my hashlink folder, so I'll be able to see if it's really an HL issue or a lime issue with pulling that file in

**Comment by Geokureli** [comment]
@MSGhero, I would very much appreciate if you could take a look.

> So maybe it should add an exception for like #if !hl or something?

@Cheemsandfriends in Funkin and some other repos, I added `#if newgrounds` checks. because it's always a good idea to allow your game to run without components, then you can just do `<haxelib name="newgrounds" if"hl/>`

**Comment by Cheemsandfriends** [comment]
> 
> 
> @MSGhero, I would very much appreciate if you could take a look.
> 
> > So maybe it should add an exception for like #if !hl or something?
> 
> @Cheemsandfriends in Funkin and some other repos, I added `#if newgrounds` checks. because it's always a good idea to allow your game to run without components, then you can just do `<haxelib name="newgrounds" unless"="hl"/>`

@Geokureli That's actually a very good idea, At least temporarily,
But there's gonna be an automatic thing so you don't have add the `#if newgrounds`
and the `<haxelib name="newgrounds" unless"="hl"/>`
or make a Newgrounds template with the `NGiox.h`, and the `Project.xml` ready,
(I don't know if you can make custom tpl's but yeah lol)

**Comment by Cheemsandfriends** [comment]
> 
> 
> I can try this out since I use HL quite a bit now with heaps. There's an ssl.hdll in my hashlink folder, so I'll be able to see if it's really an HL issue or a lime issue with pulling that file in

@MSGhero I was told from the Haxe Community place that it has that issue.

**Comment by MSGhero** [comment]
I compiled a js-only game to HL and added HL to the list of supported targets for the API (`#if !(js || flash || desktop || neko || hl)`). Otherwise it would immediately error out at that line.

I don't crash, and it attempts the login. However, I only receive the `onPending` callback and not the others. I haven't done http in HL so I'm not sure if NGAPI's approach is correct on this target. I left it for a few minutes and I didn't receive a timeout error or anything like that.

**Comment by Geokureli** [comment]
try not supplying a onPending callback. when none is supplied it auto-opens the portal webpage, when one is supplied it assumed you're opening the passport page manually and notifying the API to check for login

**Comment by MSGhero** [comment]
Nothing traces in that case. The call isn't blocking the game, and I did set `debug` to true in the API creation call. In this case, nothing traced.

**Comment by MSGhero** [comment]
Edit edit: when I trace `http.onData` I do receive what I assume is a reply from the server. See below, with my app id and stuff hidden.

```
{"success":true,"app_id":"myAppID","result":{"component":"App.startSession","data":{"success":true,"session":{"id":"mySessionID","user":null,"expired":false,"remember":false,"passport_url":"https:\/\/www.newgrounds.com\/passport\/remote\/mySessionID"},"debug":true}},"debug":{"exec_time":0.011289119720458984,"input":{"app_id":"myAppID","debug":true,"call":{"component":"App.startSession","parameters":{"force":true}}}}}
```

**Comment by Geokureli** [comment]
this sounds like it's fixed, wanna PR that `#if !(hl)` change? Looks like Cheemsandfriends was dead on!

**Comment by MSGhero** [comment]
I can PR it to resolve this issue.

In general though, I'm not seeing the passport page still. I was expecting it to be the same as when I did openfl+hxcpp, where the passport browser page opens up automatically and allowing access gives me all the callbacks. But that can be a separate issue.

**Comment by Cheemsandfriends** [comment]
> I can PR it to resolve this issue.
> 
> In general though, I'm not seeing the passport page still. I was expecting it to be the same as when I did openfl+hxcpp, where the passport browser page opens up automatically and allowing access gives me all the callbacks. But that can be a separate issue.

Nice

**Comment by Cheemsandfriends** [comment]
> this sounds like it's fixed, wanna PR that `#if !(hl)` change? Looks like Cheemsandfriends was dead on!

What do you mean with dead on?? I'm alive I swear!
