### ISSUE TITLE
HL functionality

### ISSUE THREAD

**Issue by MSGhero** [Geokureli/Newgrounds#54]
There is at least one place where HL target doesn't have an implementation. https://github.com/Geokureli/Newgrounds/blob/master/lib/Source/io/newgrounds/NG.hx#L233

I haven't checked for other ifdefs yet, but dealing with all of them would be the solution for this issue. This is something I can work on.

**Comment by Geokureli** [comment]
pretty sure I copied this from lime's https://github.com/haxelime/lime/blob/develop/src/lime/system/System.hx#L315

**Comment by Cheemsandfriends** [comment]
@Geokureli I guess you can try with flash.lib.getURL and URL request?
At least is what FlxG uses for opening Links and it works for hl and for Windows and stuff

**Comment by Geokureli** [comment]
> @Geokureli I guess you can try with flash.lib.getURL and URL request? At least is what FlxG uses for opening Links and it works for hl and for Windows and stuff

I don't want to require openfl to use this. if possible lets just copy their code, if it works on hl

**Comment by MSGhero** [comment]
Even for debugging, it would be nice to see that the API calls are working. HL/C and even hxcpp take forever to compile, so the faster feedback is good. 

The HL solution is probably the same as the Windows or Sys solution I imagine. That doesn't go through OpenFL's `getURL()` even if you're using OpenFL.

**Comment by Cheemsandfriends** [comment]
@MSGhero Yeah, I thought that flash wasn't dependent of openfl if it wasn't flash itself

**Comment by Geokureli** [comment]
fixed by #53
