### ISSUE TITLE
Add Support for Cloud Saves

### ISSUE THREAD

**Issue by Prismisho** [Geokureli/Newgrounds#60]
Tom Fulp announced yesterday that Cloud Saves is now available in the Newgrounds API. https://www.newgrounds.com/bbs/topic/1507547
When will this be in the Haxe Platform?

**Comment by Geokureli** [comment]
Oh wow, I hadn't seen this yet, this is super exciting!

at a glance, it doesn't seem too complicated, I would love to start on this soon, however, my schedule is a bit erratic right now as I'm dealing with some family issues.

I'll update this thread when I start

**Comment by MSGhero** [comment]
@Geokureli Lmk if you want some help, I've gotten so many comments in my games that this would solve. I'll have time starting next week.

**Comment by Geokureli** [comment]
started this today, coming along nicely, I'll get a WIP up either tonight or tomorrow morning. feedback welcome

**Comment by Geokureli** [comment]
WIP, needs a lot of documentation, SaveSlots will need event dispatchers and likely some checks to ensure the data size under the limit.
https://github.com/Geokureli/Newgrounds/tree/cloud-saves

check SimpleTest.hx for examples:
https://github.com/Geokureli/Newgrounds/blob/cloud-saves/test/Source/io/newgrounds/test/SimpleTest.hx#L44
works similarly to medals and scoreboards
https://github.com/Geokureli/Newgrounds/blob/cloud-saves/test/Source/io/newgrounds/test/SimpleTest.hx#L94-L131

The caveat here is that loading the slots data doesn't load the actual saved data, it loads a url to the save file. I'm wondering if `NG.core.requestSaveSlots` should have an arg to load the data for each active save slot. For most games this is tiny. Most games will have 3 slots, each capped at 2mb, devs with supporter status will have 10 slots, each capped at 8mb, which is still pretty small.

Of course you  can still use NG_LITE and do `NG.core.calls.cloudSave.loadSlot` and do everything manually.

Lastly, handling this feature just like the other helper tools (medals and scores) highlights some issues with the current system. after this feature is released, I want to consider the next major version of the newground.io haxelib

**Comment by Geokureli** [comment]
https://github.com/Geokureli/Newgrounds/commit/60bd0cc7d3f4fa2196d1e57ac3ec4d01907c5af1
took this in a new direction, after this is released I want to retroactively change scoreboards and medals to work this way
rather than `NG.core.requestSaveSlots` having a success callback and a fail callback, it just has a single callback with an enum value of either `Error(msg:String)` or `Success`, similarly, `SaveSlot` object's `load`, `save` and `clear` now have a similar callback system
