### ISSUE TITLE
Bug in ScoreBoardList.hx

### ISSUE THREAD

**Issue by Dxgamer7405** [Geokureli/Newgrounds#68]
![IMG_20220918_200337](https://user-images.githubusercontent.com/95672691/190933787-1d39ed63-f06d-4a0d-acbf-cb5d13653fa7.jpg)
How to solve this?

**Comment by Geokureli** [comment]
I renamed `sendExternal` to `sendExternalAppId`, last night. 

I'm getting ready to release 2.0, so things might change as I try to finalize things

**Comment by Geokureli** [comment]
Should be fixed now, sorry about that.
